"use strict";

// NxN array of arrays with a tile map for each level (e.g. [mob, floor])
// 'tiles' contain { icon } -> info about the character or glyph that represents them
const { worldmap } = parseMap(`
#G_#_,,#GG#TTTT..TTTT.......................
#__#______#..........T......................
#UU#______#............T....................
##+#______#.................................
__________#.G...............................
##__GG____+....K............................
#,,#______#.G...............................
#,,_______#..T.......TT.....................
#__G______#.T.......TT......................
#GG______G#........T........................
###########......TTT........................
................T...........................
............TT..T...........................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
............................................
`);

function parseMap(mapString2D) {
  const mapArray = mapString2D
    .trim()
    .split("\n")
    .map((l) => Array.from(l.trim()))
    .map((row, _yIdx) =>
      row.map((icon, _xIdx) =>
        isPlatform(icon) ? [{ icon }] : [{ icon }, defaultTile()]
      )
    );

  return {
    worldmap: mapArray,
    asString: () =>
      mapArray
        .map((row) => row.map((tile) => getTopIcon(tile)).join(""))
        .join("\n"),
  };
}

function isPlatform(icon) {
  return [".", "_"].includes(icon) || icon === "+";
}
function defaultTile() {
  return { icon: "." };
}
function emptyTile() {
  return { icon: "0" };
}
function getTopIcon(tile) {
  return tile[0]?.icon;
}
const playerLocation = { x: 15, y: 5 };

const getIconAt = ({ x, y }) => worldmap[y]?.[x]?.[0]?.icon;
const popTileAt = ({ x, y }) => worldmap[y]?.[x]?.shift() || emptyTile();
const placeTileAt = ({ tile, location }) =>
  (tile !== undefined ||
    (() => {
      throw Error(`cannot place undefined tile at ${location}`);
    })()) &&
  worldmap[location.y]?.[location.x]?.unshift(tile) &&
  location;

const canMoveOver = ({ x, y }) => isPlatform(getIconAt({ x, y }));
const moveTile = ({ from, to }) => {
  if (canMoveOver({ ...to })) {
    const tile = popTileAt({ ...from });
    return placeTileAt({ tile, location: to });
  }
};

const getAdjacentLocation = ({ location, direction }) => {
  const moveVector =
    {
      left: { x: -1, y: 0 },
      right: { x: 1, y: 0 },
      up: { x: 0, y: -1 },
      down: { x: 0, y: 1 },
    }[direction] ||
    (() => {
      throw Error(`bad direction '${direction}'`);
    })();
  return {
    x: location.x + moveVector.x,
    y: location.y + moveVector.y,
  };
};

const walkDirection = ({ location, direction }) => {
  const target = getAdjacentLocation({ location, direction });
  const finalLocation =
    moveTile({
      from: location,
      to: target,
    }) || location;

  return finalLocation;
};

export { getIconAt, walkDirection, parseMap, playerLocation };
